name: Deploy with Secrets

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Create Secret File
      run: |
        mkdir -p secret
        echo '{"BOT_TOKEN":"${{ secrets.TELEGRAM_BOT_TOKEN }}","CHAT_ID":"${{ secrets.TELEGRAM_CHAT_ID }}"}' > secret/telegram-config.json
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./